local client = require("grannos.client")

describe("client.check_protocol_compat", function()
  it("returns nil when the server's major version matches the client's", function()
    assert.is_nil(client.check_protocol_compat(client.PROTOCOL_VERSION))
  end)

  it("returns nil when the server's minor version differs but major matches", function()
    local client_major = client.PROTOCOL_VERSION:match("^(%d+)")
    assert.is_nil(client.check_protocol_compat(client_major .. ".99"))
  end)

  it("returns a warning when the server's major version differs", function()
    local warning = client.check_protocol_compat("999.0")
    assert.is_not_nil(warning)
    assert.truthy(warning:match("protocol version mismatch"))
  end)

  it("returns a warning when the server predates protocol versioning (nil)", function()
    local warning = client.check_protocol_compat(nil)
    assert.is_not_nil(warning)
    assert.truthy(warning:match("pre%-versioning server"))
  end)
end)

describe("client exit handler", function()
  it("fires when the backend process exits and clears the running state", function()
    local calls = {}
    client.set_exit_handler(function(code) table.insert(calls, code) end)
    client.start([[sh -c 'exit 3']])
    assert.is_true(client.is_running())
    vim.wait(5000, function() return #calls > 0 end, 20)
    client.set_exit_handler(nil)
    assert.are.same({ 3 }, calls)
    assert.is_false(client.is_running())
  end)

  it("reports the exit to in-flight requests before the handler runs", function()
    local events = {}
    client.set_exit_handler(function() table.insert(events, "exit") end)
    client.start("cat")
    client.request("capabilities", {}, function(err, _) table.insert(events, err) end)
    client.stop()
    vim.wait(5000, function() return #events >= 2 end, 20)
    client.set_exit_handler(nil)
    assert.are.same({ "backend exited", "exit" }, events)
  end)
end)
