#!/usr/bin/env python3
"""Generate lua/grannos/builtins/mongo.lua from MongoDB's MQL specifications.

Every name, description and argument comes from mongodb/mql-specifications —
the language-neutral YAML MongoDB keeps as "the source of truth for MongoDB
Query Language (MQL) operator specifications", from which its drivers' query
builders are generated. Nothing is written here by hand:

  definitions/<category>/*.yaml   one operator each: its name, description,
                                  minimum server version, how its arguments
                                  are encoded, and each argument's name,
                                  optionality and description

The `search` category (Atlas Search operators, named without `$`) is left out:
they are keys of a `$search` stage, which completion does not reach.

The repository has no tags, so REF is a commit.

Usage:  scripts/gen_mongo_builtins.py [git-ref]      (default: REF below)

Needs PyYAML.
"""

from __future__ import annotations

import io
import sys
import tarfile
import urllib.request
from pathlib import Path

import yaml

REF = "3b8ea5297f3c85e9fbcea81787f8f0cd16053345"
TARBALL = "https://codeload.github.com/mongodb/mql-specifications/tar.gz/{ref}"
OUT = Path(__file__).resolve().parent.parent / "lua" / "grannos" / "builtins" / "mongo.lua"

# The categories kept, each a directory under definitions/.
CATEGORIES = ["stage", "query", "update", "accumulator", "expression"]


class Loader(yaml.SafeLoader):
    """SafeLoader that reads the BSON tags the definitions' tests use
    (`!bson_utcdatetime`, …) as null: only the operator's own fields are kept."""


Loader.add_multi_constructor("!", lambda _loader, _suffix, _node: None)


def fetch(ref: str) -> dict[str, list[dict]]:
    """category → its operator definitions, from the repository at `ref`."""
    with urllib.request.urlopen(TARBALL.format(ref=ref)) as resp:
        data = resp.read()
    out: dict[str, list[dict]] = {c: [] for c in CATEGORIES}
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        for member in tar.getmembers():
            parts = member.name.split("/")
            # <repo>-<sha>/definitions/<category>/<name>.yaml
            if len(parts) == 4 and parts[1] == "definitions" and parts[2] in out \
                    and parts[3].endswith(".yaml"):
                out[parts[2]].append(yaml.load(tar.extractfile(member).read(), Loader))
    return out


def text(s: str | None) -> str:
    """A description as plain lines: the block's trailing newline dropped, and
    a line the YAML broke mid-sentence (it ends in a space) joined to the next."""
    s = (s or "").strip()
    while " \n" in s:
        s = s.replace(" \n", " ")
    return "\n".join(line.strip() for line in s.split("\n"))


def placeholder(arg: dict) -> str:
    """An argument as the signature writes it: its name, `?` when optional,
    and the repetition its `variadic` encoding allows."""
    name = arg["name"] + ("?" if arg.get("optional") else "")
    if arg.get("variadic") == "array":
        return f"{name}, ..."
    if arg.get("variadic") == "object":
        return f"<{arg['name']}>: ..., ..."
    return name


def signature(op: dict) -> str:
    """How the operator is written, from its `encode`: named arguments in an
    object, positional ones in an array, or its one argument as the value."""
    args = op.get("arguments") or []
    name, encode = op["name"], op["encode"]
    if encode == "object":
        return f"{name}: {{ {', '.join(placeholder(a) for a in args)} }}" if args else f"{name}: {{}}"
    if encode == "array":
        return f"{name}: [ {', '.join(placeholder(a) for a in args)} ]"
    if not args:
        return f"{name}: {{}}"
    arg = args[0]
    if arg.get("variadic") == "array":
        return f"{name}: [ {placeholder(arg)} ]"
    if arg.get("variadic") == "object":
        return f"{name}: {{ {placeholder(arg)} }}"
    return f"{name}: <{arg['name']}>"


def lua_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def main() -> None:
    ref = sys.argv[1] if len(sys.argv) > 1 else REF
    definitions = fetch(ref)

    lines = [
        "--- MongoDB operators — aggregation stages, query, update, accumulator and",
        "--- expression operators — for completion and hover.",
        "---",
        "--- GENERATED by scripts/gen_mongo_builtins.py from mongodb/mql-specifications",
        f"--- at {ref[:12]}: definitions/<category>/*.yaml (names, descriptions,",
        "--- minimum versions, argument encodings and descriptions). Do not edit by",
        "--- hand; rerun the script to update.",
        "---",
        "--- @class MongoBuiltinArg",
        "--- @field name     string",
        "--- @field optional boolean",
        "--- @field doc      string",
        "---",
        "--- @class MongoBuiltin",
        "--- @field signature   string             how it is written, built from its argument encoding",
        "--- @field doc         string             may hold several lines",
        "--- @field min_version string             the first MongoDB version that has it",
        "--- @field args        MongoBuiltinArg[]  the documented arguments, in order",
        "",
        "return {",
        "  --- category → name → operator. One name may be in several categories",
        "  --- (`$set` is a stage and an update operator), each with its own entry.",
        "  --- @type table<string, table<string, MongoBuiltin>>",
        "  categories = {",
    ]
    counts = []
    for category in CATEGORIES:
        ops = sorted(definitions[category], key=lambda op: op["name"])
        counts.append(f"{len(ops)} {category}")
        lines.append(f"    {category} = {{")
        for op in ops:
            lines.append(f"      [{lua_string(op['name'])}] = {{")
            lines.append(f"        signature   = {lua_string(signature(op))},")
            lines.append(f"        doc         = {lua_string(text(op['description']))},")
            lines.append(f"        min_version = {lua_string(str(op['minVersion']))},")
            documented = [a for a in op.get("arguments") or [] if a.get("description")]
            if documented:
                lines.append("        args        = {")
                for a in documented:
                    lines.append(f"          {{ name = {lua_string(a['name'])}, "
                                 f"optional = {'true' if a.get('optional') else 'false'}, "
                                 f"doc = {lua_string(text(a['description']))} }},")
                lines.append("        },")
            else:
                lines.append("        args        = {},")
            lines.append("      },")
        lines.append("    },")
    lines.append("  },")
    lines.append("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(Path.cwd()) if OUT.is_relative_to(Path.cwd()) else OUT}: "
          + ", ".join(counts))


if __name__ == "__main__":
    main()
